### PR TITLE
Code tidyup

### PR DESCRIPTION
**Pull request by IanSB**
I've done a bit of code tidying up:
1. switched 3/6BPP and 4/8BPP table selection logic
Previously the sampling object selected the table based on the frame buffer bit size of 4 or 8bpp and the frame buffer capture code selected 3 or 6 bit loops based on the sampling size read out of the sampling object which was a bit backwards.
Now the sampling object selects 3 or 6 bit tables and the capture code selects the 4 or 8 bit loops.
(Please check with the Atom adapter)

2. Implement cpld->old_firmware_support to make the old firmware support independent of the CPLD type and version (addresses https://github.com/hoglet67/RGBtoHDMI/issues/68 )

3. Remove the odd and even bits from flags register R3 to free up some bit space. They were only used by the soon to be removed odd and even sampling modes so I modified them to have separate odd and even loops instead.

### CODE REVIEW

**Comment by IanSB** [comment]
I've also added a font size option as mentioned in https://github.com/hoglet67/RGBtoHDMI/issues/92

The settings are:
Always 8x8 - always uses the 8x8 font
Auto 12x20 4bpp - will use 12x20 font if screen big enough and 4bpp mode
Auto 12x20 8bpp - will use 12x20 font if screen big enough in both 4bpp and 8bpp modes

NOTE: use in 8bpp modes causes every other frame to drop (see my sideways scrolling test) but doesn't seem to cause any other issues although I haven't done much testing
The default profile has been updated with new setting.

**Comment by IanSB** [comment]
I think we should be looking to do a release soon as my PC testers have started to receive their boards and will be looking for software shortly. We need to do some regression testing to make sure it still behaves on the old CPLD and also the Wiki needs updating.

**Comment by hoglet67** [comment]
Many thanks for doing the font option.

I agree now is a good time for a release. 

Looking at how I had named the previous releases, this one would be
- Early Adopter Release #6

Are you OK with that, or should we start to name releases?

The documentation does need a lot of work. Basically we need a User Manual (v3). Do you think the existing format is still appropriate:
https://github.com/hoglet67/RGBtoHDMI/wiki/RGBtoHDMI-User-Guide-(v2)
(possibly it should be split across several pages)

**Comment by IanSB** [comment]
> Are you OK with that, or should we start to name releases?

Should be OK for now, maybe we should switch to names when the PCB is updated to properly support 6 bit mode. Also there are still a few things left to do like implement the proper in band palette control and full NTSC artifacting.
I've tested some simple NTSC artifacting code and it works but the quality is not great so I've been looking at the NTSC artifacting code in Dosbox as that does a good job but it may be too complex to do on the Pi.

**Pull request merged**
