### PR TITLE
Add border, colour & invert options and fix issue with border scanlines

### PR DESCRIPTION
**Pull request by IanSB**
These commits add the following menu options:
Output colour: Normal / Monochrome / Green / Amber
Converts RGB to mono, or green/amber screen emulation (might need some work on getting green/amber colours exactly right).  This could be expanded to cover some of the other palette options like red only, not red etc as they currently ony relate to the standard RGB palette.
Output invert: off / on
Inverts the output
Both the above should work with any palette
Border: 0-127
Sets the logical border colour (the area that's never written to by the capture code). Mainly used for zx80/81 white background

Also scanlines in the border area are now handled properly. To see the difference, run the hdmi/nula demo before and after (especially the first 2 pics & the car).
Again update profiles to the latest

There is also a warning ("Interpolation recommended") put on the status line if any scaling option other than integer scaling is selected with interpolation off as that can look poor quality without interpolation.

Note: I moved the palette option into settings and scaling into processing to illustrate my suggestions in https://github.com/hoglet67/RGBtoHDMI/issues/87 but they can easily be moved back again.

### CODE REVIEW

**Comment by hoglet67** [comment]
I'm seeing some issues with this on the Beeb (using the default BBC_Micro profile).

Initially the menu come up normally.

Pressing auto configure cause the border and whole screen to flash white (with scanlines) during the operation. The autoconfigure does work though.

After that's been done, the same artefact appears when ever the menu is brought up.

Happens in both Modes 0-6 and Mode 7.

**Comment by IanSB** [comment]
That should be fixed now.
The menu half of the palette is now being used to display variable intensity scanlines which means when scanlines are enabled every other line has the top bit of each pixel set. Before displaying OSD info, scanlines have to be disabled and the top bit on those lines must be cleared by calling clear_menu_bits() so I have added that to the auto calibration and HDMI calibration code. Also the NO_SCANLINES bit wasn't being set when calling rgb_to_fb() from the calibration routines and it is now.

**Comment by IanSB** [comment]
Just found an issue with the sync inversion bit while testing loss of sync on the ZX80 so don't merge just yet

**Comment by IanSB** [comment]
I think that should be OK to merge now unless you find any other issues.

**Comment by IanSB** [comment]
I've implemented the double width frame buffers and it mostly works but there is an issue with the frame buffer init code.
The FB size option has 4 settings:
Normal
Double Height
Double Width
Double Height+Width
All seem to work OK except Double Width.

When that is selected  init_framebuffer(capinfo) returns with the pitch set wrong with resulting messed up screen (it seems to follow the pitch of the previous successful call.
Here are the logs snippets for each option (using bbc mode0 on a 1600x1200 monitor 8bpp)
You must change the settings in this order:

Normal
INFO: Initialised Framebuffer
INFO: Size: 800x300
INFO: Pitch: 800 bytes

Double Height
INFO: Initialised Framebuffer
INFO: Size: 800x600
INFO: Pitch: 800 bytes

Double Width
INFO: Initialised Framebuffer
INFO: Size: 1600x300
INFO: Pitch: 800 bytes      <-- should be 1600

Double Height+Width
INFO: Initialised Framebuffer
INFO: Size: 1600x600
INFO: Pitch: 1600 bytes

if you reverse order and go back to Double Width you get the right value and a good image
INFO: Initialised Framebuffer
INFO: Size: 1600x300
INFO: Pitch: 1600 bytes

but the going back to Double Height crashes
INFO: Initialised Framebuffer
INFO: Size: 800x600
INFO: Pitch: 1600 bytes    <-- should be 800

If you save the config with the value set to Double Width and reset, it starts up OK
If Double Width is omitted from the options, the other three seem to cycle OK.

**Comment by IanSB** [comment]
As it seemed sensitive to the previous size of the frame buffer I added a call to the mailbox to setup a dummy 64x64 frame buffer before calling the mailbox again to setup the actual frame buffer size and that seems to work. Any idea what's going on here?

**Comment by hoglet67** [comment]
> As it seemed sensitive to the previous size of the frame buffer I added a call to the mailbox to setup a dummy 64x64 frame buffer before calling the mailbox again to setup the actual frame buffer size and that seems to work. Any idea what's going on here?

Absolutely no idea.

Possibly an obscure Pi Firmware bug?

Work-around seems reasonable.

**Pull request merged**
