### PR TITLE
Update capture_line_default_4bpp.S

### PR DESCRIPTION
**Pull request by dp111**
simplified code slightly

### CODE REVIEW

**Comment by hoglet67** [comment]
Hi Dom,

Thanks for this. I've just tested it and it seems there is a problem with the change to the 8bpp file. Specifically, it's a performance problem rather than a coding problem.

I've tried to narrow it dowm, and it seems that changing from:

```
        tst    r3, #BIT_SCANLINES
        movne  r6, #0
        moveq  r6, r10
        str    r6, [r0, r2]
        str    r10, [r0], #4
```
to
```
        tst    r3, #BIT_SCANLINES
        strne  r6, [r0, r2]
        streq  r10, [r0, r2]
        str    r10, [r0], #4
```
seems to cause more stalling such that sampling jitter becomes apparent.

I did wonder if the the existing code was marginal, so I changed:
```
        push    {lr}
```
to
```
        push    {r0-r12, lr}
```
If it were marginal, that extra stacking of registers on entry might be expected to push it over the edge. It didn't though.

Any thoughts?

**Comment by hoglet67** [comment]
Here's another data point.

This suffers from slightly worse sampling jitter:
```
capture_line_default_8bpp:

        push    {lr}

        mov    r12, r0                   // pointer to the line in the frame buffer
        mov    r6, r1                    // number of 8-bit characters per line
loop:

        WAIT_FOR_PSYNC_10

        CAPTURE_BITS

        // Line double always in Modes 0-6 regardless of interlace
        // On the multi core Pi this introduces stalling artefacts
        str    r10, [r12, r2]
        str    r10, [r12], #4

        WAIT_FOR_PSYNC_01

        CAPTURE_BITS

        // Line double always in Modes 0-6 regardless of interlace
        // On the multi core Pi this introduces stalling artefacts
        str    r10, [r12, r2]
        str    r10, [r12], #4

        subs   r6, r6, #1
        bne    loop

exit:
        pop    {pc}
```
Where as my original version, with additional instructions intermingled, doesn't.

**Comment by hoglet67** [comment]
And another data point - it only happens with H_OFFSET being an even value. This is looking like a bug where I'm starting on the wrong edge of PSYNC. I'll check the code....

**Comment by dp111** [comment]
I would be interested to see if this is any better.

capture_line_default_4bpp:
push {lr}
mov r6, #0
mov r7, #0
tst r3, #BIT_VSYNC_MARKER
ldrne r7, =0x11111111
loop:
WAIT_FOR_PSYNC_10 // expects GPLEV0 in r4, result in r8
CAPTURE_LOW_BITS // input in r8, result in r10, corrupts r9/r14

orr r10, r10, r7
WAIT_FOR_PSYNC_01 // expects GPLEV0 in r4, result in r8
CAPTURE_HIGH_BITS // input in r8, result in r10, corrupts r9/r14
// Line double always in Modes 0-6 regardless of interlace
// On the multi core Pi this introduces stalling artefacts
#ifndef HAS_MULTICORE
tst r3, #BIT_SCANLINES
streq r10, [r0, r2]
strne r6, [r0, r2]
#endif subs r1, r1, #1
str r10, [r0], #4
bne loop
pop {pc}

**Comment by hoglet67** [comment]
Dom,

I'm slightly confused - the performance problem was only with the 8bpp version. You've just switched to the 4bpp version.

Dave

**Comment by dp111** [comment]
sorry

See my branch patch1 for a possible new version to try.

**Comment by hoglet67** [comment]
Can't see anything on patch-1:
https://github.com/dp111/RGBtoHDMI/commits/patch-1

Did you push?

**Comment by dp111** [comment]
Sorry again patch2 branch

**Comment by hoglet67** [comment]
Your last change in patch-2 made no difference to the sampling jitter.

However,  going back to the previous version in patch-2 and adding two consecutive NOPs pretty much anywhere in the loop removes the sampling jitter (one NOP is not sufficient).

That doesn't make a lot of sense to me, because the loop is paced anyway by psync edges.

I wonder if the store buffer is very close to overflowing, and adding the NOPs just prevents that happening, thus avoiding a much more expensive pipeline stall.

**Comment by hoglet67** [comment]
This also seems to work:
```
// The capture line function is provided the following:
//   r0 = pointer to current line in frame buffer
//   r1 = number of 8-pixel blocks to capture (=param_chars_per_line)
//   r2 = frame buffer line pitch in bytes (=param_fb_pitch)
//   r3 = flags register
//   r4 = GPLEV0 constant
//   r5 = frame buffer height (=param_fb_height)
//   r6 = scan line count modulo 10
//
// All registers are available as scratch registers (i.e. nothing needs to be preserved)

capture_line_default_8bpp:

        push    {lr}

        mov     r7, #0
        tst     r3, #BIT_VSYNC_MARKER
        ldrne   r7, =0x01010101

        add     r2, r0
loop:   
        WAIT_FOR_PSYNC_10

        CAPTURE_BITS

        // Orr in the VSync indicator
        orr  r5, r10, r7

        WAIT_FOR_PSYNC_01

        CAPTURE_BITS
   
        // Orr in the VSync indicator
        orr    r10, r10, r7

        str    r5,  [r0], #4
        str    r10, [r0], #4
   
        tst    r3,  #BIT_SCANLINES  
        movne  r5,  #0
        movne  r10, #0
        str    r5,  [r2], #4
        str    r10, [r2], #4

        subs   r1, r1, #1
        bne    loop

exit:
        pop    {pc}
```

**Comment by dp111** [comment]
Its complex.

in the last case the eq case has two cycles between the executed stores.
the ne case I suspect gets combined in the write buffer into one. ne eq ne
eq is too spaced out to combine ?

Try using STM

        stmia    r0!,{r5, r10}

        tst    r3,  #BIT_SCANLINES
        movne  r5,  #0
        movne  r10, #0

        stmia   r2!,{r5, r10}

**Comment by hoglet67** [comment]
Using STM works as well.

I also added 100 NOPs after the stores and that didn't cause it to break. So I don't think the loop as a whole is marginal.

Anyway, this is useful for understanding (or not!).

But the problem I would really like to solve is more efficient pattern for rendering the OSD.

In modes 0..6 we have to resort to redraw the OSD each frame, in the vertical blanking. Which means we must use multiple buffering, or it flickers really badly.

What I was thinking of trying was rending the OSD once to normal cacheable memory, and then trying to merge this into the line as the capture is happening. Odd and even lines have different OSD data, so there might need to be two read pointers, but they will both be reading sequentially. Do you think there is any chance that would work?

**Comment by dp111** [comment]
Given there is 100 spare cycles , I think putting the OSD in cacheable and
merging should be easily possible.  Also I think we have r11 and r12 free
so we aren't short of registers

**Pull request merged**
