### PR TITLE
Amiga adapter with support for SuperDenise

### PR DESCRIPTION
**Pull request by c0pperdragon**
After receiving some feedback of users with an actual SuperDenise chip, this adapter version can now be considered to work.

### CODE REVIEW

**Comment by dRwH0** [comment]
Awesome work. Can you also list the BOM for this with your selections from Farnell or similar ?

**Comment by hoglet67** [comment]
Just to say I've not forgotton this pull request.

I'll merge it back to master after we have merged the current development branch.

**Comment by SirCathal** [comment]
I can confirm that it works fine with the normal and the super Denise Chip. 
Would be great if you could accept the pull request.

**Comment by hoglet67** [comment]
Sorry for the delay.

**Pull request merged**
