### PR TITLE
Change RN1&2 to 4K7

### PR DESCRIPTION
**Pull request by IanSB**

### CODE REVIEW

**Comment by hoglet67** [comment]
Ian,

I've just tried to merge this and I'm getting some conflicts.

I think your dev branch was out of date, and didn't include a pair of commits I pushed yesterday (9th), which did some profile renaming (Atom and ZX80).

I can try to unpick this tomorrow morning, as I'm tied up with other things.

Dave
```
git merge ian/dev
CONFLICT (rename/rename): Rename "src/scripts/Profiles/RGB(TTL)/ZX80_(TTL).txt"->"src/scripts/Profiles/RGB(TTL)/ZX80.txt" in branch "HEAD" rename "src/scripts/Profiles/RGB(TTL)/ZX80_(TTL).txt"->"src/scripts/Profiles/6BIT_RGB/ZX80_(TTL).txt" in "ian/dev"
Removing src/scripts/Profiles/RGB(TTL)/QL.txt
CONFLICT (rename/delete): src/scripts/Profiles/OBBC/Atom_50HzTTL_v24.txt deleted in HEAD and renamed to src/scripts/Profiles/Legacy_3BIT/Atom_50HzTTL_v24.txt in ian/dev. Version ian/dev of src/scripts/Profiles/Legacy_3BIT/Atom_50HzTTL_v24.txt left in tree.
CONFLICT (rename/delete): src/scripts/Profiles/OBBC/Atom_50HzTTL_v21-v23.txt deleted in HEAD and renamed to src/scripts/Profiles/Legacy_3BIT/Atom_50HzTTL_v21-v23.txt in ian/dev. Version ian/dev of src/scripts/Profiles/Legacy_3BIT/Atom_50HzTTL_v21-v23.txt left in tree.
CONFLICT (rename/delete): src/scripts/Profiles/OBBC/Atom_50HzTTL_v10-v20.txt deleted in HEAD and renamed to src/scripts/Profiles/Legacy_3BIT/Atom_50HzTTL_v10-v20.txt in ian/dev. Version ian/dev of src/scripts/Profiles/Legacy_3BIT/Atom_50HzTTL_v10-v20.txt left in tree.
CONFLICT (rename/rename): Rename "src/scripts/Profiles/BBC/ZX80_(TTL).txt"->"src/scripts/Profiles/BBC/ZX80.txt" in branch "HEAD" rename "src/scripts/Profiles/BBC/ZX80_(TTL).txt"->"src/scripts/Profiles/3BIT_RGB/ZX80_(TTL).txt" in "ian/dev"
Removing src/scripts/Profiles/BBC/QL.txt
CONFLICT (rename/delete): src/scripts/Profiles/RGB(TTL)/Atom_50HzTTL.txt deleted in HEAD and renamed to src/scripts/Profiles/6BIT_RGB/Atom_50HzTTL.txt in ian/dev. Version ian/dev of src/scripts/Profiles/6BIT_RGB/Atom_50HzTTL.txt left in tree.
CONFLICT (rename/delete): src/scripts/Profiles/BBC/Atom_50HzTTL.txt deleted in HEAD and renamed to src/scripts/Profiles/3BIT_RGB/Atom_50HzTTL.txt in ian/dev. Version ian/dev of src/scripts/Profiles/3BIT_RGB/Atom_50HzTTL.txt left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by IanSB** [comment]
OK I think I've sorted it out

**Comment by hoglet67** [comment]
> OK I think I've sorted it out

I'm still seeing conflicts, but a smaller number, just around the renaming of the ZX80 profile:
```
git merge ian/dev
CONFLICT (rename/rename): Rename "src/scripts/Profiles/RGB(TTL)/ZX80_(TTL).txt"->"src/scripts/Profiles/RGB(TTL)/ZX80.txt" in branch "HEAD" rename "src/scripts/Profiles/RGB(TTL)/ZX80_(TTL).txt"->"src/scripts/Profiles/6BIT_RGB/ZX80.txt" in "ian/dev"
Removing src/scripts/Profiles/RGB(TTL)/QL.txt
Removing src/scripts/Profiles/RGB(Analog)/ZX80_(TTL).txt
Removing src/scripts/Profiles/RGB(Analog)/UK_101_(TTL).txt
CONFLICT (rename/rename): Rename "src/scripts/Profiles/BBC/ZX80_(TTL).txt"->"src/scripts/Profiles/BBC/ZX80.txt" in branch "HEAD" rename "src/scripts/Profiles/BBC/ZX80_(TTL).txt"->"src/scripts/Profiles/3BIT_RGB/ZX80.txt" in "ian/dev"
Removing src/scripts/Profiles/BBC/QL.txt
Automatic merge failed; fix conflicts and then commit the result.
```
Dave

**Comment by IanSB** [comment]
I just pulled from your dev, merged and pushed back to my dev without any conflicts.

I've decided to keep the ability to change the interface setting as I might do another interface in future and it now saves separate entries for each CPLD as it was too easy to lose the setting when changing CPLD and going back again.
I've left the old UA1/UB1 setting in for the moment to test these changes.

**Comment by hoglet67** [comment]
Ian,

That's sorted the conflicts.

I'm not sure how you did the earlier merge, but the reason I was getting conflicts was because the commit that was pushed wasn't a proper merge commit (which has two parents). You second merge worked, because it does have two parents (one of which is the tip of my dev branch). Anyway, thans for sorting this out.

See also my comments in #140 

Dave

**Pull request merged**
